### ISSUE TITLE
signature file pulled from dotfiles references reyhan.org - bug or feature? :-) 

### ISSUE THREAD

**Issue by cenau** [rey/.i3#11]
https://raw.githubusercontent.com/rey/.dot/master/signature

**Comment by cenau** [comment]
There are probably a few bits and pieces like this coming from the dotfiles - eg, the git identity https://github.com/rey/.dot/blob/master/gitconfig#L19

**Comment by rey** [comment]
@cenau good call :+1:

**Comment by rey** [comment]
Consolidated into https://github.com/rey/computer/issues/12
