### ISSUE TITLE
bash complains that `-bash: /Users/rey/.rvm/scripts/rvm: No such file or directory`

### ISSUE THREAD

**Issue by cenau** [rey/.i3#9]
bash complains that
`-bash: /Users/rey/.rvm/scripts/rvm: No such file or directory`

on login. 

looks like the .bash_profie from the .dot repo references  hardcoded user dir:
https://github.com/rey/.dot/blob/c224a9584d5111a96da29036431a61e3e058438a/bash_profile#L2

**Comment by rey** [comment]
@cenau true say, this is due to a lazy line in my `.bashrc` https://github.com/rey/.dot/blob/master/bashrc#L17

I'll fix that.

**Comment by rey** [comment]
Consolidated into https://github.com/rey/computer/issues/12
